repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace

# rst
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal

# javascript
-   repo: https://github.com/pre-commit/mirrors-fixmyjs
    rev: v2.0.0
    hooks:
    -   id: fixmyjs
-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.13.0
    hooks:
    -   id: jshint
